version: "3"

services:
  db:
    container_name: octonn_db
    image: postgres:14.4-bullseye
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
      OCTONN_DB: octonn_db
      OCTONN_USER: octonn
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - octonn_data:/var/lib/postgresql/data
      - ../scripts/postgres/initdb:/docker-entrypoint-initdb.d:ro
      - ../OctoNN/scripts/migrate:/scripts/migrate/:ro

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  octonn_data: