version: "3"

services:
  db:
    container_name: octonn_db
    image: postgres:14.4-bullseye
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
      OCTONN_DB: octonn_db
      OCTONN_USER: octonn
      MIGRATION_PATH: /scripts/migrate
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - octonn_data:/var/lib/postgresql/data
      - ../scripts/postgres/initdb:/docker-entrypoint-initdb.d:ro
      - ../app/scripts/migrate:/scripts/migrate:ro

  redis:
    image: redis:7.0.4-bullseye
    container_name: octonn-redis
    ports:
      - "6379:6379"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    volumes:
      - redis_data:/data

volumes:
  octonn_data:
  redis_data: